<a href="https://colab.research.google.com/github/AnshumanAI/NLP-LLMs/blob/main/Attention_calc(self).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import math

In [13]:
L, k,v=4,8,8
Q=np.random.randn(L,k)
K=np.random.randn(L,k)
V=np.random.randn(L,v)

In [20]:
P=np.matmul(Q,K.T)
P

array([[ 2.74753199,  1.87799812,  0.68500382,  1.91193503],
       [-0.61229974, -0.94778134,  1.71694228,  1.3962999 ],
       [-0.96387046, -2.37694049,  4.48543335,  0.63527204],
       [-4.08184667, -9.06032819,  5.4050504 , -3.30224597]])

In [21]:
Scaled=P/math.sqrt(k)
Scaled.var()

1.4635050032050145

In [22]:
mask=np.tril(np.ones((L,L)))
mask[mask==0]=-np.infty
mask[mask==1]=0
mask
#without mask , row will sum to 1 I guess

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [24]:
S=Scaled+mask
S

array([[ 0.97139925,        -inf,        -inf,        -inf],
       [-0.21648065, -0.33509131,        -inf,        -inf],
       [-0.34077967, -0.84037537,  1.58584017,        -inf],
       [-1.44315073, -3.20330975,  1.9109739 , -1.16752026]])

In [25]:
#softmax
def softmax(X):
    return (np.exp(X).T/np.sum(np.exp(X),axis=-1)).T

In [26]:
Attention=softmax(S)
New_V=np.matmul(Attention,V)
print(V,"_"*10,"\n")
print(New_V)

[[-0.16501795 -0.97053276  0.63230295  0.93722243 -0.49079291 -0.5230579
   0.09131539 -1.42342207]
 [-1.67896291 -1.90022402  0.19776651  0.7227473   1.68108693 -0.93034948
  -0.98174398  0.75616533]
 [ 0.03968828  0.69749234 -0.72803349 -2.25177905  1.55756884 -0.43980499
  -0.7633519  -0.82725071]
 [ 1.38675696  0.60675164  0.5980037  -1.58092831 -0.29558505 -1.75913724
   0.92737054  0.43230129]] __________ 

[[-0.16501795 -0.97053276  0.63230295  0.93722243 -0.49079291 -0.5230579
   0.09131539 -1.42342207]
 [-0.87715049 -1.40784284  0.42790481  0.83633718  0.53082039 -0.71464055
  -0.41343248 -0.39818328]
 [-0.10754846  0.31460052 -0.50118574 -1.66239511  1.32466372 -0.48475977
  -0.67812246 -0.78421923]
 [ 0.08064728  0.62566907 -0.62303611 -2.1044169   1.41393661 -0.50106108
  -0.66549269 -0.78432264]]
